### PR TITLE
Direct use of nearest neighbor results

### PR DESCRIPTION
**Pull request by LTLA**
This attempts to address #32 by passing the KNN information (a list of 2 matrices, one for indices and another for distances) to the `computeGaussianPerplexity` function. The idea is to do something like:

```r
library(Rtsne)
iris_unique <- unique(iris) # Remove duplicates
iris_matrix <- as.matrix(iris_unique[,1:4])

set.seed(42) # Set a seed if you want reproducible results
tsne_out <- Rtsne(iris_matrix, perplexity=10, pca=FALSE, max_iter=1) # Run TSNE

library(FNN)
blah <- sweep(iris_matrix, 2, colMeans(iris_matrix), "-") # mimic normalization inside Rtsne.
blah <- blah/max(abs(blah))
nn30 <- get.knn(blah, k=30)
set.seed(42)
tsne_alt <- Rtsne(iris_matrix, nearest_neighbors=nn30, perplexity=10, pca=FALSE, max_iter=1)

summary(tsne_out$Y - tsne_alt$Y)
##        V1                   V2            
##  Min.   :-1.338e-06   Min.   :-1.019e-06  
##  1st Qu.: 0.000e+00   1st Qu.: 0.000e+00  
##  Median : 0.000e+00   Median : 0.000e+00  
##  Mean   : 0.000e+00   Mean   : 0.000e+00  
##  3rd Qu.: 0.000e+00   3rd Qu.: 0.000e+00  
##  Max.   : 2.106e-06   Max.   : 7.620e-07  
```

Several points:

- I resisted the temptation to refactor `computeGaussianPerplexity`, and just copy-and-pasted the code for the per-observation iteration steps. As a result, there's a lot of redundancy here.
- Despite my best efforts, the two `Y` matrices in the example above don't exactly match up even after 1 iteration, presumably due to numerical imprecision in the distances. After thousands of iterations, these differences amplify quite a bit, though the results still look qualitatively comparable.
- From looking at the C++ code, it seems as if supplying the NN information circumvents the need for the original data matrix entirely. I wasn't entirely sure of this, but if this is the case, then the nearest neighbor information could be directly passed as `X`. However, if not, some more consideration would be required to ensure that the data matrix and the nearest neighbor information is properly synchronized. Indeed, the normalization step is not exposed to the user and will affect the computed distances.

### CODE REVIEW

**Comment by jkrijthe** [comment]
I see I have done the refactor in the openmp branch, but did not merge it into the main branch yet. Would be good to see how we can integrate your changes with those.

The numerical precision issue has been somewhat of a recurring theme when debugging/testing as well, although it would be nice if at least the first few iterations line up.

I'm not sure what interface makes the most sense. Indeed if you do not need the data matrix for the computations, then it could make sense to pass the knn distances as the X object instead (and perhaps the knn indices as the nearest_neighbour argument).

**Comment by LTLA** [comment]
Having thought about it for a bit, there may be some opportunities for a more aggressive refactoring that effectively asks the C++ code to start from the nearest neighbor result in all cases. One would then move the existing NN calculations to a separate function that gets called in R to generate `nearest_neighbor`, if it is not already supplied. This avoid having to write a separate handler for NN results, given that the NN results seem to be "necessary and sufficient" for `computeGaussianPerplexity`. (Indeed, you wouldn't need the `X` matrix at all, allowing the raw data wrangling to be performed wholly in R.) However, it would involve some considerable modifications from the van der Maaten source, so it's your call.

On an unrelated note, looking at the code indicates that there's quite a few of `calloc`s and `new`s in the evaluation and gradient functions. Perhaps some more speed could be squeezed out if we avoided repeated memory allocations and `free`ing, e.g., by wrapping everything in a class, with a member data structure that persists across calls. Of course, this would involve even more refactoring.

**Comment by jkrijthe** [comment]
Thanks for those suggestions! I agree your first suggestion could work, but indeed it would take us a bit further from the original implementation (which we have slowly drifted away from anyway, but this might be too big a change for me to currently see the impact of). As for the second suggestion: I do not have any experience with this, bit if it helps performance, it could be worth exploring.

Would you mind if I first merge in the refactor from the openmp branch later this week, before adapting your changes? I'm sorry for the inconvenience.

**Comment by LTLA** [comment]
No problems. If it has too many conflicts, I'll just redo it fresh from the new `master`. The change wasn't particularly complicated anyway, and now that we've started this refactoring conversation, we might have some opportunities to change the code in a more considered way.

**Comment by jkrijthe** [comment]
I got around to merging the changes from the openmp branch over the weekend. Again, sorry about the conflicts this caused.

**Comment by LTLA** [comment]
No probs. I'll close this and have a look at the new C++ code; I'll put forward a more concrete plan of action (w.r.t. any potential refactoring) for discussion before I do anything.

**Pull request closed without merging**
