### PR TITLE
Rtsne(): add traces= option

### PR DESCRIPTION
**Pull request by alyst**
If `traces=TRUE` (`FALSE` by default), adds to the output of `Rtsne()` `Y_traces` array of size `(no_dims, N, max_iter+1)` containing embedded coordinates at each t-SNE iteration (the first one being the initial positions).

It could be used to visualize the optimization process (either for debugging or just because it looks fancy).

### CODE REVIEW

**Comment by jkrijthe** [comment]
Thanks! Two questions: 1. is there a particular reason you prefer this interface over a callback, like how it's done in the tsne package, and discussed in issue #20? 2. Would it make sense to add an option to write the coordinates every nth iteration instead of every iteration?

**Comment by alyst** [comment]
1. I suppose it's easier to implement than the callback. I needed it to see the whole optimization process, so for this purpose it's also the most efficient alternative. But callback is a good idea in general, is there some WIP implementation already?
2. Sure, I can add support for e.g. `trace=n`, where `n` is the `n` iteration, if you approve the PR in general. Then we would also need to return the list of iterations which were traced.

**Comment by jkrijthe** [comment]
1. I was testing an implementation of the callback (by passing an Rcpp::Function object) locally. Seems to work, although I find your suggestion reasonable as well. Was just wondering which makes the most sense, especially for datasets with many objects.
2. Perhaps we could combine this with having the itercosts evaluations done every nth iteration as well, where it is currently fixed at every 50th iteration.

**Comment by jkrijthe** [comment]
Thanks again for the PR. Based on the discussion in #20, I think the callback option would be more consistent with other implementations at this point.

**Pull request closed without merging**
