### PR TITLE
Support direct use of NN results for TSNE

### PR DESCRIPTION
**Pull request by LTLA**
This is a demonstrative PR of the changes to be made to the _Rtsne_ code to support the direct use of NN results in the t-SNE perplexity calculations (attempting to address #39, again). Note that the new C++ code has not yet been connected to the rest of the code. Edits welcome.

### CODE REVIEW

**Comment by jkrijthe** [comment]
I agree this looks reasonable. I am a bit wary of these types of changes because it makes it somewhat harder to incorporate important changes from the upstream implementation. However, it does look nice and modular. Perhaps the allocateMemory function should get a different name, given that it is a rather generic name for the specific memory allocation being done.

**Comment by LTLA** [comment]
Yes, I share your concerns about upstream changes, though this is tempered somewhat by their infrequency. The last update in _bhtsne_ was 2 years ago, which is a pretty long time for such a widely used piece of code.

The best solution would be to include some of these changes (possibly including the openMP stuff) in the original t-SNE C++ source; but I guess this is too much to ask, especially if it breaks some non-R stuff.

As for `allocateMemory`: I suspect it might be even better to move that particular function's contents into `TSNE::run`, which ensures that memory is allocated in the same place that it gets `free`d. This should make it even easier to follow the logic. (Why `malloc` is used instead of `std::vector` is a bit of a mystery to me.)

**Comment by LTLA** [comment]
You should be able to do:

```r
library(Rtsne)
iris_unique <- unique(iris) # Remove duplicates
iris_matrix <- as.matrix(iris_unique[,1:4])

library(FNN)
NN <- get.knn(iris_matrix, 90)
set.seed(42) 
out <- Rtsne:::Rtsne_nn_cpp(t(NN$nn.index - 1L), t(NN$nn.dist), origD=ncol(iris_matrix), no_dims=2,
    Y_in=matrix(), init=FALSE, perplexity = 30, theta = 0.5, max_iter = 1000,
    verbose = getOption("verbose", FALSE),
    stop_lying_iter = 250L, mom_switch_iter = 250L, 
    momentum = 0.5, final_momentum = 0.8, eta = 200, exaggeration_factor = 12, num_threads = 1)
plot(out$Y,col=iris_unique$Species)
```

As I mentioned before, this is not quite equal to running `Rtsne(iris_matrix)` directly, possibly due to amplification of differences from numerical imprecision with the distances in the nearest neighbour search. At least for testing purposes, we can double-check this by writing an _Rcpp_ wrapper for the ball-tree search and feeding it back into `Rtsne_nn_cpp`; this should then yield exactly the same results.

I should also explain some of the commits above:

- I added a separate interface in the `TSNE` class to take the NN results as input. I had tried to keep everything in one function but this became very cluttered, with lots of conditional statements that made it difficult to follow.
- I moved a few of the arguments and temporary arrays into member variables of the `TSNE` class. This reduces the number of arguments that need to be passed to internal functions, which makes for some easier reading.
- The separate `Rtsne_nn_cpp` interface is just to avoid breaking the `Rtsne_cpp` with extra arguments. This could be merged into a single function, there's not much work in those functions anyway.

**Comment by jkrijthe** [comment]
I would have preferred the change to be a bit less invasive, but if this makes for a better interface and we test it extensively, it could be fine.

Do you get the same result as when feeding the dist(iris_matrix) object to Rtsne?

**Comment by LTLA** [comment]
Yeah, my apologies with respect to the extent of the modifications. I had hoped to keep the changes contained, but my discipline slipped at points when I couldn't help but convert things into more idiomatic C++.

And yes, I agree that if we have enough tests, we should be fine. One simple (off-line) approach would be to test it against the reference (_bhtsne_) Python implementation, using a pre-supplied `init` matrix to avoid issues with random number generation. If this works, it would give us a great deal of confidence in our refactoring.

Finally - after much struggle - I have managed to get the NN mode consistent with the precomputed distance:

```r
set.seed(101)
library(Rtsne)
iris_matrix <- matrix(rnorm(150*4), nrow=150) # See note 1

library(FNN)
NN <- get.knn(iris_matrix, 90)
D <- as.matrix(dist(iris_matrix))
re.nn <- NN$nn.dist
for (i in seq_len(ncol(re.nn))) {
    re.nn[,i] <- D[cbind(seq_len(nrow(re.nn)), NN$nn.index[,i])] 
}
range(re.nn - NN$nn.dist) # check it gives 0 0; no numerical precision problems here.

Y_in <- matrix(runif(nrow(iris_matrix)*2), ncol=2) # See note 2

par(mfrow=c(1,2))
set.seed(42) 
out <- Rtsne:::Rtsne_nn_cpp(t(NN$nn.index - 1L), t(NN$nn.dist), origD=ncol(iris_matrix), no_dims=2,
    Y_in=Y_in, init=TRUE, perplexity = 30, theta = 0.5, max_iter = 1000,
    verbose = TRUE,
    stop_lying_iter = 250L, mom_switch_iter = 250L, 
    momentum = 0.5, final_momentum = 0.8, eta = 200, exaggeration_factor = 12, num_threads = 1)
plot(out$Y)

set.seed(42) 
blah <- Rtsne(D, is_distance=TRUE, verbose=TRUE, max_iter=1000,
    stop_lying_iter=250L, mom_switch_iter=250L, Y_init=Y_in) # See note 3
plot(blah$Y)
```

1. The original `iris_matrix` has a few tied distances, which alters the order of nearest neighbours. This then alters the order of addition when computing various statistics, which results in small rounding errors that are amplified across t-SNE iterations. Hence, I have to simulate a case where no ties are possible.
2. The `vptree` involves a few `R::runif` calls, which alters the seed in the precomputed distance case. This results in different random initialization of `Y`. Thus, we need to supply a pre-computed `Y` as well.
3. `stop_lying_iter` and `mom_switch_iter` flip their default values in `Rtsne` depending on whether `Y_init` is supplied, so we force them to be consistent with the values in `Rtsne_nn_cpp`.

**Comment by LTLA** [comment]
I set up a test suite: https://github.com/LTLA/RtsneTestSuite. Some more hacks are necessary to get coverage for the momentum and "stop lying" behaviour, but it looks like it matches up well for the first few iterations.

**Comment by LTLA** [comment]
Formally added a new interface, `Rtsne_neighbors`. I've put it in a separate function call as the nature of the input is quite different to the others, and some arguments are simply not relevant when dealing with NN input; having a separate interface eliminates the potential for confusion about parameter combinations. I've also added tests that compare to the precomputed distance case, and updated the documentation accordingly.

**Comment by jkrijthe** [comment]
Sounds good. Are you planning any other changes for this PR? If not, I can see whether I have some time in the coming weeks to go over the proposed changes.

**Comment by jkrijthe** [comment]
Thanks again for the PR. As I mentioned, I find the changes to the structure of the code fairly extensive, given the importance of the feature. That said, I think I understand the changes well enough to merge them into the main branch.

**Comment by LTLA** [comment]
Much appreciated @jkrijthe. I think this also means that #32 can be closed - perhaps @gokceneraslan could indicate whether this satisfies his use-case.

**Comment by gokceneraslan** [comment]
So it's just `Rtsne_neighbors(indices, distances)`, right? Haven't tried but looks great, exactly what I need! Thanks a lot!

**Pull request merged**
