### PR TITLE
Optionally skip test requiring irlba

### PR DESCRIPTION
**Pull request by MichaelChirico**

### CODE REVIEW

**Comment by SamGG** [comment]
If the goal is to ignore the test when irlba is not installed, why the skip is not at the first line of the test?

**Comment by MichaelChirico** [comment]
oh, I just noticed there's no expect* unit tests before there in the same test_that call.

still, some Rtsne model is fit, at least running without error is a weak test itself.

**Comment by jkrijthe** [comment]
Never ran into this, since (I would hope) anyone running these tests would want to runt the irlba tests as well. For completeness, I guess it's fine to add the skip, but I agree with SamGG that it make more sense to then skip the full test, instead of still computing the reference (I think the check whether the reference runs is sufficiently covered by the other tests).

**Comment by SamGG** [comment]
IIRC, these are recent problems with the irlba package as stated in uwot also.

**Comment by MichaelChirico** [comment]
Moved the skip.

We only add new packages on an as-needed basis, so Suggests are typically not brought in unless they're specifically used elsewhere -- hasn't happened (yet) for irlba, hence running into this test failure.

**Comment by jkrijthe** [comment]
Thanks for the clarification. The failing check is unrelated to this change. Thanks for the PR!

**Pull request merged**
